add_test( [==[OSM: New -> PendingNew via Submit]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: New -> PendingNew via Submit]==]  )
set_tests_properties( [==[OSM: New -> PendingNew via Submit]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingNew -> Accepted via Acknowledge]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingNew -> Accepted via Acknowledge]==]  )
set_tests_properties( [==[OSM: PendingNew -> Accepted via Acknowledge]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingNew -> Rejected via Reject]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingNew -> Rejected via Reject]==]  )
set_tests_properties( [==[OSM: PendingNew -> Rejected via Reject]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Accepted -> PartiallyFilled via PartialFill]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Accepted -> PartiallyFilled via PartialFill]==]  )
set_tests_properties( [==[OSM: Accepted -> PartiallyFilled via PartialFill]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Accepted -> Filled via Fill]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Accepted -> Filled via Fill]==]  )
set_tests_properties( [==[OSM: Accepted -> Filled via Fill]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Accepted -> PendingCancel via RequestCancel]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Accepted -> PendingCancel via RequestCancel]==]  )
set_tests_properties( [==[OSM: Accepted -> PendingCancel via RequestCancel]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Accepted -> Expired via Expire]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Accepted -> Expired via Expire]==]  )
set_tests_properties( [==[OSM: Accepted -> Expired via Expire]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Accepted -> PendingReplace via RequestReplace]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Accepted -> PendingReplace via RequestReplace]==]  )
set_tests_properties( [==[OSM: Accepted -> PendingReplace via RequestReplace]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PartiallyFilled -> PartiallyFilled via PartialFill]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PartiallyFilled -> PartiallyFilled via PartialFill]==]  )
set_tests_properties( [==[OSM: PartiallyFilled -> PartiallyFilled via PartialFill]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PartiallyFilled -> Filled via Fill]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PartiallyFilled -> Filled via Fill]==]  )
set_tests_properties( [==[OSM: PartiallyFilled -> Filled via Fill]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PartiallyFilled -> PendingCancel via RequestCancel]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PartiallyFilled -> PendingCancel via RequestCancel]==]  )
set_tests_properties( [==[OSM: PartiallyFilled -> PendingCancel via RequestCancel]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingCancel -> Canceled via CancelAck]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingCancel -> Canceled via CancelAck]==]  )
set_tests_properties( [==[OSM: PendingCancel -> Canceled via CancelAck]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingCancel -> Filled via Fill (race)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingCancel -> Filled via Fill (race)]==]  )
set_tests_properties( [==[OSM: PendingCancel -> Filled via Fill (race)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingCancel -> PendingCancel via PartialFill (in-flight)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingCancel -> PendingCancel via PartialFill (in-flight)]==]  )
set_tests_properties( [==[OSM: PendingCancel -> PendingCancel via PartialFill (in-flight)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingCancel -> Accepted via Reject (cancel rejected)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingCancel -> Accepted via Reject (cancel rejected)]==]  )
set_tests_properties( [==[OSM: PendingCancel -> Accepted via Reject (cancel rejected)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingReplace -> Accepted via ReplaceAck]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingReplace -> Accepted via ReplaceAck]==]  )
set_tests_properties( [==[OSM: PendingReplace -> Accepted via ReplaceAck]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingReplace -> Accepted via Reject (replace rejected)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingReplace -> Accepted via Reject (replace rejected)]==]  )
set_tests_properties( [==[OSM: PendingReplace -> Accepted via Reject (replace rejected)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PendingReplace -> Filled via Fill (race)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PendingReplace -> Filled via Fill (race)]==]  )
set_tests_properties( [==[OSM: PendingReplace -> Filled via Fill (race)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: PartiallyFilled -> Expired via Expire]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: PartiallyFilled -> Expired via Expire]==]  )
set_tests_properties( [==[OSM: PartiallyFilled -> Expired via Expire]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: New + Fill is invalid]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: New + Fill is invalid]==]  )
set_tests_properties( [==[OSM: New + Fill is invalid]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: New + any event besides Submit is invalid]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: New + any event besides Submit is invalid]==]  )
set_tests_properties( [==[OSM: New + any event besides Submit is invalid]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Filled is terminal -- all events fail]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Filled is terminal -- all events fail]==]  )
set_tests_properties( [==[OSM: Filled is terminal -- all events fail]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Canceled is terminal -- all events fail]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Canceled is terminal -- all events fail]==]  )
set_tests_properties( [==[OSM: Canceled is terminal -- all events fail]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Rejected is terminal -- all events fail]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Rejected is terminal -- all events fail]==]  )
set_tests_properties( [==[OSM: Rejected is terminal -- all events fail]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: Expired is terminal -- all events fail]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: Expired is terminal -- all events fail]==]  )
set_tests_properties( [==[OSM: Expired is terminal -- all events fail]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: apply on Order updates state and bumps version]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: apply on Order updates state and bumps version]==]  )
set_tests_properties( [==[OSM: apply on Order updates state and bumps version]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: full lifecycle through Order object]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: full lifecycle through Order object]==]  )
set_tests_properties( [==[OSM: full lifecycle through Order object]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: cancel lifecycle through Order object]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: cancel lifecycle through Order object]==]  )
set_tests_properties( [==[OSM: cancel lifecycle through Order object]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: replace lifecycle through Order object]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: replace lifecycle through Order object]==]  )
set_tests_properties( [==[OSM: replace lifecycle through Order object]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: valid_events for New returns only Submit]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: valid_events for New returns only Submit]==]  )
set_tests_properties( [==[OSM: valid_events for New returns only Submit]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: valid_events for Filled returns empty]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: valid_events for Filled returns empty]==]  )
set_tests_properties( [==[OSM: valid_events for Filled returns empty]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: valid_events for Accepted returns expected set]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: valid_events for Accepted returns expected set]==]  )
set_tests_properties( [==[OSM: valid_events for Accepted returns expected set]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: to_string for states]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: to_string for states]==]  )
set_tests_properties( [==[OSM: to_string for states]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OSM: to_string for events]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OSM: to_string for events]==]  )
set_tests_properties( [==[OSM: to_string for events]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: order passes all checks with permissive limits]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: order passes all checks with permissive limits]==]  )
set_tests_properties( [==[RiskManager: order passes all checks with permissive limits]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: order passes with no limits configured (all zeros)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: order passes with no limits configured (all zeros)]==]  )
set_tests_properties( [==[RiskManager: order passes with no limits configured (all zeros)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: fail max order quantity]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: fail max order quantity]==]  )
set_tests_properties( [==[RiskManager: fail max order quantity]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: fail max order notional]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: fail max order notional]==]  )
set_tests_properties( [==[RiskManager: fail max order notional]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: fail max orders per second]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: fail max orders per second]==]  )
set_tests_properties( [==[RiskManager: fail max orders per second]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: fail max open orders]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: fail max open orders]==]  )
set_tests_properties( [==[RiskManager: fail max open orders]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: kill switch blocks all orders]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: kill switch blocks all orders]==]  )
set_tests_properties( [==[RiskManager: kill switch blocks all orders]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: kill switch deactivate re-enables trading]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: kill switch deactivate re-enables trading]==]  )
set_tests_properties( [==[RiskManager: kill switch deactivate re-enables trading]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: symbol-specific limits override]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: symbol-specific limits override]==]  )
set_tests_properties( [==[RiskManager: symbol-specific limits override]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: position tracking after fills]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: position tracking after fills]==]  )
set_tests_properties( [==[RiskManager: position tracking after fills]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: on_order_accepted increments open count]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: on_order_accepted increments open count]==]  )
set_tests_properties( [==[RiskManager: on_order_accepted increments open count]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: on_order_canceled decrements open count]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: on_order_canceled decrements open count]==]  )
set_tests_properties( [==[RiskManager: on_order_canceled decrements open count]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: on_order_rejected decrements tracking]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: on_order_rejected decrements tracking]==]  )
set_tests_properties( [==[RiskManager: on_order_rejected decrements tracking]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[RiskManager: to_string for results]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[RiskManager: to_string for results]==]  )
set_tests_properties( [==[RiskManager: to_string for results]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[BestPrice: routes buy to lowest ask venue]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[BestPrice: routes buy to lowest ask venue]==]  )
set_tests_properties( [==[BestPrice: routes buy to lowest ask venue]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[BestPrice: routes sell to highest bid venue]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[BestPrice: routes sell to highest bid venue]==]  )
set_tests_properties( [==[BestPrice: routes sell to highest bid venue]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[BestPrice: considers fees for buy]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[BestPrice: considers fees for buy]==]  )
set_tests_properties( [==[BestPrice: considers fees for buy]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[BestPrice: returns empty decision with no venues]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[BestPrice: returns empty decision with no venues]==]  )
set_tests_properties( [==[BestPrice: returns empty decision with no venues]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[BestPrice: returns empty decision with invalid NBBO]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[BestPrice: returns empty decision with invalid NBBO]==]  )
set_tests_properties( [==[BestPrice: returns empty decision with invalid NBBO]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[LiquiditySweep: sweeps multiple venues]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[LiquiditySweep: sweeps multiple venues]==]  )
set_tests_properties( [==[LiquiditySweep: sweeps multiple venues]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[LiquiditySweep: total quantity matches order]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[LiquiditySweep: total quantity matches order]==]  )
set_tests_properties( [==[LiquiditySweep: total quantity matches order]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[LiquiditySweep: sweeps across multiple price levels]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[LiquiditySweep: sweeps across multiple price levels]==]  )
set_tests_properties( [==[LiquiditySweep: sweeps across multiple price levels]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SmartIOC: FOK requires single venue fill]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SmartIOC: FOK requires single venue fill]==]  )
set_tests_properties( [==[SmartIOC: FOK requires single venue fill]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SmartIOC: IOC sweeps available liquidity]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SmartIOC: IOC sweeps available liquidity]==]  )
set_tests_properties( [==[SmartIOC: IOC sweeps available liquidity]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SmartIOC: respects slippage tolerance]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SmartIOC: respects slippage tolerance]==]  )
set_tests_properties( [==[SmartIOC: respects slippage tolerance]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[VWAP: produces a slice with valid market data]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[VWAP: produces a slice with valid market data]==]  )
set_tests_properties( [==[VWAP: produces a slice with valid market data]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[VWAP: multiple slices accumulate fills]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[VWAP: multiple slices accumulate fills]==]  )
set_tests_properties( [==[VWAP: multiple slices accumulate fills]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[VWAP: fill_progress and is_complete]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[VWAP: fill_progress and is_complete]==]  )
set_tests_properties( [==[VWAP: fill_progress and is_complete]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[VWAP: auto-initializes from order via route()]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[VWAP: auto-initializes from order via route()]==]  )
set_tests_properties( [==[VWAP: auto-initializes from order via route()]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Strategy type and name accessors]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Strategy type and name accessors]==]  )
set_tests_properties( [==[Strategy type and name accessors]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: empty book has invalid best bid/ask]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: empty book has invalid best bid/ask]==]  )
set_tests_properties( [==[OrderBook: empty book has invalid best bid/ask]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: add bid levels, best_bid is highest]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: add bid levels\, best_bid is highest]==]  )
set_tests_properties( [==[OrderBook: add bid levels, best_bid is highest]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: add ask levels, best_ask is lowest]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: add ask levels\, best_ask is lowest]==]  )
set_tests_properties( [==[OrderBook: add ask levels, best_ask is lowest]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: update existing bid level]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: update existing bid level]==]  )
set_tests_properties( [==[OrderBook: update existing bid level]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: remove level with qty=0]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: remove level with qty=0]==]  )
set_tests_properties( [==[OrderBook: remove level with qty=0]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: remove non-existent level is no-op]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: remove non-existent level is no-op]==]  )
set_tests_properties( [==[OrderBook: remove non-existent level is no-op]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: crossed book detection]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: crossed book detection]==]  )
set_tests_properties( [==[OrderBook: crossed book detection]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: mid_price calculation]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: mid_price calculation]==]  )
set_tests_properties( [==[OrderBook: mid_price calculation]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: spread calculation]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: spread calculation]==]  )
set_tests_properties( [==[OrderBook: spread calculation]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: quantity_at_or_better]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: quantity_at_or_better]==]  )
set_tests_properties( [==[OrderBook: quantity_at_or_better]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[OrderBook: clear resets everything]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[OrderBook: clear resets everything]==]  )
set_tests_properties( [==[OrderBook: clear resets everything]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: register venues]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: register venues]==]  )
set_tests_properties( [==[Aggregator: register venues]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: single venue book update and NBBO]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: single venue book update and NBBO]==]  )
set_tests_properties( [==[Aggregator: single venue book update and NBBO]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: NBBO across two venues]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: NBBO across two venues]==]  )
set_tests_properties( [==[Aggregator: NBBO across two venues]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: best bid from one venue, best ask from another]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: best bid from one venue\, best ask from another]==]  )
set_tests_properties( [==[Aggregator: best bid from one venue, best ask from another]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: same price at both venues accumulates quantity]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: same price at both venues accumulates quantity]==]  )
set_tests_properties( [==[Aggregator: same price at both venues accumulates quantity]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: get_aggregated_book merges venues]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: get_aggregated_book merges venues]==]  )
set_tests_properties( [==[Aggregator: get_aggregated_book merges venues]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: staleness detection with no data is stale]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: staleness detection with no data is stale]==]  )
set_tests_properties( [==[Aggregator: staleness detection with no data is stale]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: fresh data is not stale]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: fresh data is not stale]==]  )
set_tests_properties( [==[Aggregator: fresh data is not stale]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[Aggregator: NBBO callback fires on update]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[Aggregator: NBBO callback fires on update]==]  )
set_tests_properties( [==[Aggregator: NBBO callback fires on update]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[NBBO: valid() requires both sides]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[NBBO: valid() requires both sides]==]  )
set_tests_properties( [==[NBBO: valid() requires both sides]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[NBBO: spread and mid_price]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[NBBO: spread and mid_price]==]  )
set_tests_properties( [==[NBBO: spread and mid_price]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint default construction is zero]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint default construction is zero]==]  )
set_tests_properties( [==[FixedPoint default construction is zero]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint from_raw preserves raw value]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint from_raw preserves raw value]==]  )
set_tests_properties( [==[FixedPoint from_raw preserves raw value]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint from_double round-trips accurately]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint from_double round-trips accurately]==]  )
set_tests_properties( [==[FixedPoint from_double round-trips accurately]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint from_raw matches expected double]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint from_raw matches expected double]==]  )
set_tests_properties( [==[FixedPoint from_raw matches expected double]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint addition]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint addition]==]  )
set_tests_properties( [==[FixedPoint addition]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint subtraction]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint subtraction]==]  )
set_tests_properties( [==[FixedPoint subtraction]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint subtraction yields negative]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint subtraction yields negative]==]  )
set_tests_properties( [==[FixedPoint subtraction yields negative]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint multiplication]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint multiplication]==]  )
set_tests_properties( [==[FixedPoint multiplication]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint division]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint division]==]  )
set_tests_properties( [==[FixedPoint division]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint compound assignment operators]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint compound assignment operators]==]  )
set_tests_properties( [==[FixedPoint compound assignment operators]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint unary negation]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint unary negation]==]  )
set_tests_properties( [==[FixedPoint unary negation]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint comparison operators]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint comparison operators]==]  )
set_tests_properties( [==[FixedPoint comparison operators]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint edge cases]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint edge cases]==]  )
set_tests_properties( [==[FixedPoint edge cases]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FixedPoint to_double precision for typical prices]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FixedPoint to_double precision for typical prices]==]  )
set_tests_properties( [==[FixedPoint to_double precision for typical prices]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[PriceFixed uses 1e8 scale]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[PriceFixed uses 1e8 scale]==]  )
set_tests_properties( [==[PriceFixed uses 1e8 scale]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeeRate uses 1e6 scale]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeeRate uses 1e6 scale]==]  )
set_tests_properties( [==[FeeRate uses 1e6 scale]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeeRate arithmetic]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeeRate arithmetic]==]  )
set_tests_properties( [==[FeeRate arithmetic]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[to_price and to_double from types.h match FixedPoint]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[to_price and to_double from types.h match FixedPoint]==]  )
set_tests_properties( [==[to_price and to_double from types.h match FixedPoint]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: capacity and initial available]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: capacity and initial available]==]  )
set_tests_properties( [==[MemoryPool: capacity and initial available]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: allocate up to capacity]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: allocate up to capacity]==]  )
set_tests_properties( [==[MemoryPool: allocate up to capacity]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: returns nullptr when exhausted]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: returns nullptr when exhausted]==]  )
set_tests_properties( [==[MemoryPool: returns nullptr when exhausted]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: deallocate and reallocate]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: deallocate and reallocate]==]  )
set_tests_properties( [==[MemoryPool: deallocate and reallocate]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: available count tracking]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: available count tracking]==]  )
set_tests_properties( [==[MemoryPool: available count tracking]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: multiple allocate/deallocate cycles]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: multiple allocate/deallocate cycles]==]  )
set_tests_properties( [==[MemoryPool: multiple allocate/deallocate cycles]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MemoryPool: works with Order type]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MemoryPool: works with Order type]==]  )
set_tests_properties( [==[MemoryPool: works with Order type]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: empty on construction]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: empty on construction]==]  )
set_tests_properties( [==[SPSCQueue: empty on construction]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: push and pop single item]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: push and pop single item]==]  )
set_tests_properties( [==[SPSCQueue: push and pop single item]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: pop from empty returns false]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: pop from empty returns false]==]  )
set_tests_properties( [==[SPSCQueue: pop from empty returns false]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: fill to capacity]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: fill to capacity]==]  )
set_tests_properties( [==[SPSCQueue: fill to capacity]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: FIFO ordering preserved]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: FIFO ordering preserved]==]  )
set_tests_properties( [==[SPSCQueue: FIFO ordering preserved]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: interleaved push and pop]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: interleaved push and pop]==]  )
set_tests_properties( [==[SPSCQueue: interleaved push and pop]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: move semantics]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: move semantics]==]  )
set_tests_properties( [==[SPSCQueue: move semantics]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: wrap-around behaviour]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: wrap-around behaviour]==]  )
set_tests_properties( [==[SPSCQueue: wrap-around behaviour]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SPSCQueue: concurrent producer-consumer]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SPSCQueue: concurrent producer-consumer]==]  )
set_tests_properties( [==[SPSCQueue: concurrent producer-consumer]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: parse single quote message]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: parse single quote message]==]  )
set_tests_properties( [==[AlpacaNormalizer: parse single quote message]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: parse multiple quotes in one message]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: parse multiple quotes in one message]==]  )
set_tests_properties( [==[AlpacaNormalizer: parse multiple quotes in one message]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: trade messages do not generate book callbacks]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: trade messages do not generate book callbacks]==]  )
set_tests_properties( [==[AlpacaNormalizer: trade messages do not generate book callbacks]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: control messages are ignored]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: control messages are ignored]==]  )
set_tests_properties( [==[AlpacaNormalizer: control messages are ignored]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: malformed JSON is handled gracefully]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: malformed JSON is handled gracefully]==]  )
set_tests_properties( [==[AlpacaNormalizer: malformed JSON is handled gracefully]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: skip quotes with missing fields]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: skip quotes with missing fields]==]  )
set_tests_properties( [==[AlpacaNormalizer: skip quotes with missing fields]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: skip quotes with invalid values]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: skip quotes with invalid values]==]  )
set_tests_properties( [==[AlpacaNormalizer: skip quotes with invalid values]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: price conversion accuracy]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: price conversion accuracy]==]  )
set_tests_properties( [==[AlpacaNormalizer: price conversion accuracy]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: sequence numbers increment]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: sequence numbers increment]==]  )
set_tests_properties( [==[AlpacaNormalizer: sequence numbers increment]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[AlpacaNormalizer: book updates overwrite previous state]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[AlpacaNormalizer: book updates overwrite previous state]==]  )
set_tests_properties( [==[AlpacaNormalizer: book updates overwrite previous state]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: fresh monitor is stale (no messages)]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: fresh monitor is stale (no messages)]==]  )
set_tests_properties( [==[FeedQualityMonitor: fresh monitor is stale (no messages)]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: not stale after receiving message]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: not stale after receiving message]==]  )
set_tests_properties( [==[FeedQualityMonitor: not stale after receiving message]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: becomes stale after threshold]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: becomes stale after threshold]==]  )
set_tests_properties( [==[FeedQualityMonitor: becomes stale after threshold]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: counters increment correctly]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: counters increment correctly]==]  )
set_tests_properties( [==[FeedQualityMonitor: counters increment correctly]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: reset clears all counters]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: reset clears all counters]==]  )
set_tests_properties( [==[FeedQualityMonitor: reset clears all counters]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[FeedQualityMonitor: last_message_time is set after message]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[FeedQualityMonitor: last_message_time is set after message]==]  )
set_tests_properties( [==[FeedQualityMonitor: last_message_time is set after message]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MarketDataAggregator: concurrent writers and readers]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MarketDataAggregator: concurrent writers and readers]==]  )
set_tests_properties( [==[MarketDataAggregator: concurrent writers and readers]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MarketDataAggregator: concurrent register_venue and book_update]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MarketDataAggregator: concurrent register_venue and book_update]==]  )
set_tests_properties( [==[MarketDataAggregator: concurrent register_venue and book_update]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[MarketDataAggregator: NBBO callback fires under lock safely]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[MarketDataAggregator: NBBO callback fires under lock safely]==]  )
set_tests_properties( [==[MarketDataAggregator: NBBO callback fires under lock safely]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController initializes without config]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController initializes without config]==]  )
set_tests_properties( [==[SorController initializes without config]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController start/stop lifecycle]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController start/stop lifecycle]==]  )
set_tests_properties( [==[SorController start/stop lifecycle]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController submit and track order]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController submit and track order]==]  )
set_tests_properties( [==[SorController submit and track order]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController NBBO available after init]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController NBBO available after init]==]  )
set_tests_properties( [==[SorController NBBO available after init]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController kill switch toggle]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController kill switch toggle]==]  )
set_tests_properties( [==[SorController kill switch toggle]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController drain events are initially empty]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController drain events are initially empty]==]  )
set_tests_properties( [==[SorController drain events are initially empty]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController watched symbols]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController watched symbols]==]  )
set_tests_properties( [==[SorController watched symbols]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
add_test( [==[SorController fill events flow through after order]==] /home/saad/personal/klett/sor/build_gui/tests/unit/sor_unit_tests [==[SorController fill events flow through after order]==]  )
set_tests_properties( [==[SorController fill events flow through after order]==] PROPERTIES WORKING_DIRECTORY /home/saad/personal/klett/sor/build_gui/tests/unit)
set( sor_unit_tests_TESTS [==[OSM: New -> PendingNew via Submit]==] [==[OSM: PendingNew -> Accepted via Acknowledge]==] [==[OSM: PendingNew -> Rejected via Reject]==] [==[OSM: Accepted -> PartiallyFilled via PartialFill]==] [==[OSM: Accepted -> Filled via Fill]==] [==[OSM: Accepted -> PendingCancel via RequestCancel]==] [==[OSM: Accepted -> Expired via Expire]==] [==[OSM: Accepted -> PendingReplace via RequestReplace]==] [==[OSM: PartiallyFilled -> PartiallyFilled via PartialFill]==] [==[OSM: PartiallyFilled -> Filled via Fill]==] [==[OSM: PartiallyFilled -> PendingCancel via RequestCancel]==] [==[OSM: PendingCancel -> Canceled via CancelAck]==] [==[OSM: PendingCancel -> Filled via Fill (race)]==] [==[OSM: PendingCancel -> PendingCancel via PartialFill (in-flight)]==] [==[OSM: PendingCancel -> Accepted via Reject (cancel rejected)]==] [==[OSM: PendingReplace -> Accepted via ReplaceAck]==] [==[OSM: PendingReplace -> Accepted via Reject (replace rejected)]==] [==[OSM: PendingReplace -> Filled via Fill (race)]==] [==[OSM: PartiallyFilled -> Expired via Expire]==] [==[OSM: New + Fill is invalid]==] [==[OSM: New + any event besides Submit is invalid]==] [==[OSM: Filled is terminal -- all events fail]==] [==[OSM: Canceled is terminal -- all events fail]==] [==[OSM: Rejected is terminal -- all events fail]==] [==[OSM: Expired is terminal -- all events fail]==] [==[OSM: apply on Order updates state and bumps version]==] [==[OSM: full lifecycle through Order object]==] [==[OSM: cancel lifecycle through Order object]==] [==[OSM: replace lifecycle through Order object]==] [==[OSM: valid_events for New returns only Submit]==] [==[OSM: valid_events for Filled returns empty]==] [==[OSM: valid_events for Accepted returns expected set]==] [==[OSM: to_string for states]==] [==[OSM: to_string for events]==] [==[RiskManager: order passes all checks with permissive limits]==] [==[RiskManager: order passes with no limits configured (all zeros)]==] [==[RiskManager: fail max order quantity]==] [==[RiskManager: fail max order notional]==] [==[RiskManager: fail max orders per second]==] [==[RiskManager: fail max open orders]==] [==[RiskManager: kill switch blocks all orders]==] [==[RiskManager: kill switch deactivate re-enables trading]==] [==[RiskManager: symbol-specific limits override]==] [==[RiskManager: position tracking after fills]==] [==[RiskManager: on_order_accepted increments open count]==] [==[RiskManager: on_order_canceled decrements open count]==] [==[RiskManager: on_order_rejected decrements tracking]==] [==[RiskManager: to_string for results]==] [==[BestPrice: routes buy to lowest ask venue]==] [==[BestPrice: routes sell to highest bid venue]==] [==[BestPrice: considers fees for buy]==] [==[BestPrice: returns empty decision with no venues]==] [==[BestPrice: returns empty decision with invalid NBBO]==] [==[LiquiditySweep: sweeps multiple venues]==] [==[LiquiditySweep: total quantity matches order]==] [==[LiquiditySweep: sweeps across multiple price levels]==] [==[SmartIOC: FOK requires single venue fill]==] [==[SmartIOC: IOC sweeps available liquidity]==] [==[SmartIOC: respects slippage tolerance]==] [==[VWAP: produces a slice with valid market data]==] [==[VWAP: multiple slices accumulate fills]==] [==[VWAP: fill_progress and is_complete]==] [==[VWAP: auto-initializes from order via route()]==] [==[Strategy type and name accessors]==] [==[OrderBook: empty book has invalid best bid/ask]==] [==[OrderBook: add bid levels, best_bid is highest]==] [==[OrderBook: add ask levels, best_ask is lowest]==] [==[OrderBook: update existing bid level]==] [==[OrderBook: remove level with qty=0]==] [==[OrderBook: remove non-existent level is no-op]==] [==[OrderBook: crossed book detection]==] [==[OrderBook: mid_price calculation]==] [==[OrderBook: spread calculation]==] [==[OrderBook: quantity_at_or_better]==] [==[OrderBook: clear resets everything]==] [==[Aggregator: register venues]==] [==[Aggregator: single venue book update and NBBO]==] [==[Aggregator: NBBO across two venues]==] [==[Aggregator: best bid from one venue, best ask from another]==] [==[Aggregator: same price at both venues accumulates quantity]==] [==[Aggregator: get_aggregated_book merges venues]==] [==[Aggregator: staleness detection with no data is stale]==] [==[Aggregator: fresh data is not stale]==] [==[Aggregator: NBBO callback fires on update]==] [==[NBBO: valid() requires both sides]==] [==[NBBO: spread and mid_price]==] [==[FixedPoint default construction is zero]==] [==[FixedPoint from_raw preserves raw value]==] [==[FixedPoint from_double round-trips accurately]==] [==[FixedPoint from_raw matches expected double]==] [==[FixedPoint addition]==] [==[FixedPoint subtraction]==] [==[FixedPoint subtraction yields negative]==] [==[FixedPoint multiplication]==] [==[FixedPoint division]==] [==[FixedPoint compound assignment operators]==] [==[FixedPoint unary negation]==] [==[FixedPoint comparison operators]==] [==[FixedPoint edge cases]==] [==[FixedPoint to_double precision for typical prices]==] [==[PriceFixed uses 1e8 scale]==] [==[FeeRate uses 1e6 scale]==] [==[FeeRate arithmetic]==] [==[to_price and to_double from types.h match FixedPoint]==] [==[MemoryPool: capacity and initial available]==] [==[MemoryPool: allocate up to capacity]==] [==[MemoryPool: returns nullptr when exhausted]==] [==[MemoryPool: deallocate and reallocate]==] [==[MemoryPool: available count tracking]==] [==[MemoryPool: multiple allocate/deallocate cycles]==] [==[MemoryPool: works with Order type]==] [==[SPSCQueue: empty on construction]==] [==[SPSCQueue: push and pop single item]==] [==[SPSCQueue: pop from empty returns false]==] [==[SPSCQueue: fill to capacity]==] [==[SPSCQueue: FIFO ordering preserved]==] [==[SPSCQueue: interleaved push and pop]==] [==[SPSCQueue: move semantics]==] [==[SPSCQueue: wrap-around behaviour]==] [==[SPSCQueue: concurrent producer-consumer]==] [==[AlpacaNormalizer: parse single quote message]==] [==[AlpacaNormalizer: parse multiple quotes in one message]==] [==[AlpacaNormalizer: trade messages do not generate book callbacks]==] [==[AlpacaNormalizer: control messages are ignored]==] [==[AlpacaNormalizer: malformed JSON is handled gracefully]==] [==[AlpacaNormalizer: skip quotes with missing fields]==] [==[AlpacaNormalizer: skip quotes with invalid values]==] [==[AlpacaNormalizer: price conversion accuracy]==] [==[AlpacaNormalizer: sequence numbers increment]==] [==[AlpacaNormalizer: book updates overwrite previous state]==] [==[FeedQualityMonitor: fresh monitor is stale (no messages)]==] [==[FeedQualityMonitor: not stale after receiving message]==] [==[FeedQualityMonitor: becomes stale after threshold]==] [==[FeedQualityMonitor: counters increment correctly]==] [==[FeedQualityMonitor: reset clears all counters]==] [==[FeedQualityMonitor: last_message_time is set after message]==] [==[MarketDataAggregator: concurrent writers and readers]==] [==[MarketDataAggregator: concurrent register_venue and book_update]==] [==[MarketDataAggregator: NBBO callback fires under lock safely]==] [==[SorController initializes without config]==] [==[SorController start/stop lifecycle]==] [==[SorController submit and track order]==] [==[SorController NBBO available after init]==] [==[SorController kill switch toggle]==] [==[SorController drain events are initially empty]==] [==[SorController watched symbols]==] [==[SorController fill events flow through after order]==])
